name: Dispatch PR Env Results URL

'on':
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          BASE: ${{ env.ACTIONS_RESULTS_URL }}
        run: |
          echo "base_len=${#BASE}"
